version: '3'
services:
  app:
    build: .
    command: /bin/bash -c 'mix ecto.create && mix phx.server'
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: password
    links:
      - db
  db:
    image: healthcheck/postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
