version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  build:
    docker:
      - image: cimg/elixir:1.14-browsers
        environment:
          PGUSER: postgres
          PGPASSWORD: password
      - image: cimg/postgres:14.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          name: Install dependencies
          command: bin/ci_deps
      - run:
          name: Build assets
          command: bin/ci_assets
      - run:
          name: Create database
          command: bin/ci_db
      - run:
          name: Run tests
          command: mix test
 
workflows:
  build-workflow:
    jobs:
      - build
