version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  build:
    docker:
      - image: cimg/elixir:1.14-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run:
          name: Install hex
          command: mix local.hex --force
      - run:
          name: Install rebar
          command: mix local.rebar --force
      - run:
          name: Install mix deps
          command: mix deps.get
      - run:
          name: Run tests
          command: mix test
 
workflows:
  build-workflow:
    jobs:
      - build